// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// SubscriptionsColumns holds the columns for the "subscriptions" table.
	SubscriptionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "stripe_customer_id", Type: field.TypeString, Unique: true},
		{Name: "stripe_subscription_id", Type: field.TypeString, Unique: true},
		{Name: "status", Type: field.TypeString, Default: "inactive"},
		{Name: "current_period_end", Type: field.TypeTime, Nullable: true},
		{Name: "user_subscription", Type: field.TypeInt},
	}
	// SubscriptionsTable holds the schema information for the "subscriptions" table.
	SubscriptionsTable = &schema.Table{
		Name:       "subscriptions",
		Columns:    SubscriptionsColumns,
		PrimaryKey: []*schema.Column{SubscriptionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "subscriptions_users_subscription",
				Columns:    []*schema.Column{SubscriptionsColumns[5]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "clerk_user_id", Type: field.TypeString, Unique: true},
		{Name: "role", Type: field.TypeString, Default: "user"},
		{Name: "is_subscribed", Type: field.TypeBool, Default: false},
		{Name: "subscription_tier", Type: field.TypeString, Default: "free"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		SubscriptionsTable,
		UsersTable,
	}
)

func init() {
	SubscriptionsTable.ForeignKeys[0].RefTable = UsersTable
}
