import type { Metadata } from "next";
import { SpeedInsights } from "@vercel/speed-insights/next"
import { Analytics } from '@vercel/analytics/next';
import { JetBrains_Mono } from "next/font/google";
import { Inter } from "next/font/google";
import Footer from "@/components/layout/Footer";
import "./globals.css";

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Leakr",
  description:
    "Discover, manage, and organize content from your favorite creators.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${jetbrainsMono.variable} ${inter.variable} antialiased`}
      >
        <SpeedInsights />
        <Analytics /> {/* Vercel Analytics */}
        {children}
        <Footer />
      </body>
    </html>
  );
}

// Release version layout.tsx
// import type { Metadata } from 'next'
// import { ClerkProvider } from '@clerk/nextjs' // ClerkProvider stays here
// import { Geist, Geist_Mono } from 'next/font/google'
// import { Header } from '@/components/Header' // Header component is imported
// import './globals.css'

// const geistSans = Geist({
//   variable: '--font-geist-sans',
//   subsets: ['latin'],
// })

// const geistMono = Geist_Mono({
//   variable: '--font-geist-mono',
//   subsets: ['latin'],
// })

// export const metadata: Metadata = {
//   title: 'Clerk Next.js Quickstart',
//   description: 'Generated by create next app',
// }

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode
// }>) {
//   return (
//     <ClerkProvider> {/* ClerkProvider wraps the app */}
//       <html lang="en">
//         <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
//           <Header /> {/* Header component is used */}
//           {children}
//         </body>
//       </html>
//     </ClerkProvider>
//   )
// }
