name: "Test build extension"
on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - name: Use Node.js 20.x
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 20.x
          cache: "pnpm"
      - uses: pnpm/action-setup@v3
        with:
          version: 8.15.5   # or latest
      - name: Install dependencies
        run: pnpm install
      - name: Build the extension
        run: pnpm build
      - name: Package the extension into a zip artifact
        run: pnpm package
      - name: Upload the extension zip artifact
        uses: actions/upload-artifact@v4
        with:
          name: extension-package
          path: build/chrome-mv3-prod.zip
